version: '3.8'

services:
  app:
    container_name: spring-app
    image: dongledonut/skyst2025waffleuniv
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - spring-mysql-network

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: somepassword
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql-network

networks:
  spring-mysql-network:
    driver: bridge

volumes:
  db-data:
