version: '3.8'

services:
  app:
    container_name: spring-app
    image: dongledonut/skyst2025waffleuniv
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    network_mode: "host"

  mysql:
    image: mysql:8.4
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
    # TODO: these values should be moved to a separate file
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: somepassword
    volumes:
      - db-data:/var/lib/mysql
    network_mode: "host"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-p$$MYSQL_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db-data:
