spring:
  datasource:
    url: 'jdbc:mysql://127.0.0.1:3306/testdb'
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: user
    password: somepassword
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  profiles:
    active: dev

  security:
    jwt-secret: AAAAAAAAAAAAAAAAAAAAAAAAADSFaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

#cache: # Use if we implement Caffeine caching
#  expire-after-write: 1m
#  maximum-size: 100

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
